# Базовый контейнер у меня - это php с нужной мне версией в нужной мне сборке
FROM php:7.4-fpm

# Назначаю рабочую папку проекта (/var/www/html - стандарт для nginx сервера)
WORKDIR /var/www/html


# обновляю систему и ставлю unzip и другие мелкие утилиты
RUN apt update && apt install -y unzip curl mc


# Что бы я мог пользоваться компосером - я его ставлю в момент сборки контейнера
# скопировать composer из контейнера
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# скачать инсталяцию и установить его по другому методу
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Загружаем приложение в докер контейнер
COPY . /var/www/html
