version: '3'

services:
  rabbit:
    image: rabbitmq:3.12.4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_SERVER=rabbit.mq
      - RABBITMQ_PORT=5672


networks:
  pv121_java:
    driver: bridge