version: '3'

services:
  db.mysql:
    build:
      dockerfile: ./dockers/mysql/DockerFile
    # Для доступа к базе данных мне нужно предоставить доступ к порту
    # Мы описываем правило - внутренний порт: внешний порт
    # Эта операция не нужна, если доступ в базу снаружи (вне докера) не нужен
    ports:
      - 3306:3306
    # Подключаю внешнее хранилище во внутреннюю папку. Таким образом данные будут
    # лежать файлы базы. Если этого не сделать - то докер создат место сам
    volumes:
      - ./volumes/db/mysql:var/lib/mysql
    # Переменные для настройки сервиса (я узнаю из документации https://hub.docker.com/_/mysql
    # Я могу прописать их тут, или в .env файле
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - xampp8



networks:
  xampp8:
    driver: bridge
